-- AIFinder production schema. Run once in Supabase SQL Editor as project owner.
-- This file contains the complete, hardened schema with Row Level Security (RLS),
-- security definer functions, automated triggers, and role-based access control.
-- Deliberately contains no service-role key or privileged client secret.

-- 1. PROFILES TABLE (Linked to auth.users)
create table if not exists public.profiles (
  id uuid primary key references auth.users(id) on delete cascade,
  full_name text not null default '',
  role text not null default 'user' check (role in ('user', 'admin')),
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

-- Helper function: Check if current authenticated user is an administrator
create or replace function public.is_admin()
returns boolean language sql stable security definer set search_path = public
as $$ select exists (select 1 from public.profiles where id = auth.uid() and role = 'admin') $$;

-- Trigger: auto-update updated_at timestamp
create or replace function public.set_updated_at()
returns trigger language plpgsql set search_path = public
as $$ begin new.updated_at = now(); return new; end; $$;

-- Trigger: automatically create public.profiles entry upon signup in auth.users
create or replace function public.create_profile_for_user()
returns trigger language plpgsql security definer set search_path = public
as $$
begin
  insert into public.profiles (id, full_name, role)
  values (
    new.id,
    coalesce(left(coalesce(new.raw_user_meta_data ->> 'full_name', new.raw_user_meta_data ->> 'name', ''), 120), ''),
    'user'
  )
  on conflict (id) do nothing;
  return new;
end;
$$;

drop trigger if exists on_auth_user_created on auth.users;
create trigger on_auth_user_created after insert on auth.users
for each row execute procedure public.create_profile_for_user();

-- 2. TOOLS TABLE (Curated Directory Catalog)
create table if not exists public.tools (
  id bigint generated by default as identity primary key,
  name text not null check (char_length(btrim(name)) between 2 and 120),
  emoji text not null default '🤖' check (char_length(emoji) <= 16),
  category text not null check (category in ('writing','image','code','video','audio','research','productivity','customer','data','education','marketing','other')),
  category_label text not null check (char_length(category_label) <= 80),
  pricing text not null default 'freemium' check (pricing in ('free','freemium','paid','enterprise')),
  pricing_label text not null default 'Freemium' check (char_length(pricing_label) <= 32),
  rating numeric(2,1) not null default 0 check (rating >= 0 and rating <= 5),
  rating_count integer not null default 0 check (rating_count >= 0),
  description text not null check (char_length(description) between 10 and 3000),
  tags jsonb not null default '[]'::jsonb check (jsonb_typeof(tags) = 'array'),
  features jsonb not null default '[]'::jsonb check (jsonb_typeof(features) = 'array'),
  website text not null check (website ~* '^https://'),
  has_api boolean not null default false,
  has_freeplan boolean not null default true,
  status text not null default 'approved' check (status in ('approved','pending','archived')),
  submitted_by uuid references auth.users(id) on delete set null,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

-- Unique index for duplicate prevention
alter table public.tools add column if not exists normalized_name text generated always as (lower(btrim(name))) stored;
create unique index if not exists tools_normalized_name_key on public.tools(normalized_name);

-- 3. SUBMISSIONS TABLE (Community Moderation Queue)
create table if not exists public.submissions (
  id bigint generated by default as identity primary key,
  user_id uuid not null references auth.users(id) on delete cascade,
  name text not null check (char_length(btrim(name)) between 2 and 120),
  category text not null check (category in ('writing','image','code','video','audio','research','productivity','customer','data','education','marketing','other')),
  category_label text not null check (char_length(category_label) <= 80),
  website text not null check (website ~* '^https://'),
  pricing text not null default 'freemium' check (pricing in ('free','freemium','paid','enterprise')),
  submitter_email text not null default '',
  description text not null check (char_length(description) between 10 and 3000),
  features jsonb not null default '[]'::jsonb check (jsonb_typeof(features) = 'array'),
  status text not null default 'pending' check (status in ('pending','approved','rejected')),
  admin_notes text,
  submitted_at timestamptz not null default now(),
  reviewed_at timestamptz,
  updated_at timestamptz not null default now()
);

-- 4. REVIEWS TABLE (Authenticated User Ratings & Reviews)
create table if not exists public.reviews (
  id bigint generated by default as identity primary key,
  tool_id bigint not null references public.tools(id) on delete cascade,
  user_id uuid not null references auth.users(id) on delete cascade,
  user_name text not null default '',
  rating integer not null check (rating between 1 and 5),
  review_text text not null check (char_length(btrim(review_text)) between 20 and 2000),
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  unique (tool_id, user_id)
);

-- 5. SIGN-IN AUDIT LOGS TABLE
create table if not exists public.sign_in_logs (
  id bigint generated by default as identity primary key,
  user_id uuid not null references auth.users(id) on delete cascade,
  email text not null,
  role text not null check (role in ('user','admin')),
  user_name text,
  signed_in_at timestamptz not null default now(),
  auth_provider text not null default 'email' check (auth_provider in ('email','oauth')),
  ip_address inet,
  user_agent text
);

-- Indexes for optimal query performance
create index if not exists idx_tools_public on public.tools(status, created_at desc);
create index if not exists idx_submissions_owner on public.submissions(user_id, submitted_at desc);
create index if not exists idx_reviews_tool on public.reviews(tool_id, created_at desc);
create index if not exists idx_signins_time on public.sign_in_logs(signed_in_at desc);

-- Functions & Triggers for Data Preparation and Aggregation
create or replace function public.prepare_submission()
returns trigger language plpgsql security definer set search_path = public
as $$
begin
  new.user_id := auth.uid();
  new.submitter_email := coalesce(auth.jwt() ->> 'email', '');
  new.status := 'pending';
  new.reviewed_at := null;
  new.admin_notes := null;
  return new;
end;
$$;

create or replace function public.prepare_review()
returns trigger language plpgsql security definer set search_path = public
as $$
begin
  new.user_id := auth.uid();
  new.user_name := coalesce((select full_name from public.profiles where id = auth.uid()), split_part(coalesce(auth.jwt() ->> 'email','Member'), '@', 1));
  return new;
end;
$$;

create or replace function public.refresh_tool_rating()
returns trigger language plpgsql security definer set search_path = public
as $$
declare affected_tool bigint := coalesce(new.tool_id, old.tool_id);
begin
  update public.tools set
    rating = coalesce((select round(avg(rating)::numeric, 1) from public.reviews where tool_id = affected_tool), 0),
    rating_count = (select count(*) from public.reviews where tool_id = affected_tool)
  where id = affected_tool;
  return coalesce(new, old);
end;
$$;

-- Secure procedure to record sign in events from authenticated users
create or replace function public.record_my_sign_in(p_user_agent text default null)
returns void language plpgsql security definer set search_path = public
as $$
begin
  if auth.uid() is null then raise exception 'Authentication required'; end if;
  insert into public.sign_in_logs(user_id, email, role, user_name, auth_provider, user_agent)
  select auth.uid(), coalesce(auth.jwt() ->> 'email',''), p.role, p.full_name,
    case when coalesce(auth.jwt() ->> 'provider','email') = 'email' then 'email' else 'oauth' end,
    left(coalesce(p_user_agent, ''), 512)
  from public.profiles p where p.id = auth.uid();
end;
$$;

-- Secure procedure to approve a submission and publish it to tools catalog
create or replace function public.approve_submission(p_submission_id bigint)
returns public.tools language plpgsql security definer set search_path = public
as $$
declare sub public.submissions; published public.tools;
begin
  if not public.is_admin() then raise exception 'Administrator authorization is required'; end if;
  select * into sub from public.submissions where id = p_submission_id and status = 'pending' for update;
  if not found then raise exception 'Pending submission not found'; end if;
  insert into public.tools (name, emoji, category, category_label, pricing, pricing_label, rating, rating_count, description, tags, features, website, has_api, has_freeplan, status, submitted_by)
  values (sub.name, '🚀', sub.category, sub.category_label, sub.pricing,
    initcap(sub.pricing), 0, 0, sub.description, jsonb_build_array('Community submission', sub.category), sub.features,
    sub.website, false, sub.pricing in ('free','freemium'), 'approved', sub.user_id)
  on conflict (normalized_name) do update set updated_at = now()
  returning * into published;
  update public.submissions set status = 'approved', reviewed_at = now() where id = sub.id;
  return published;
end;
$$;

-- Attach lifecycle triggers
drop trigger if exists submissions_prepare on public.submissions;
create trigger submissions_prepare before insert on public.submissions for each row execute procedure public.prepare_submission();

drop trigger if exists reviews_prepare on public.reviews;
create trigger reviews_prepare before insert on public.reviews for each row execute procedure public.prepare_review();

drop trigger if exists tools_updated_at on public.tools;
create trigger tools_updated_at before update on public.tools for each row execute procedure public.set_updated_at();

drop trigger if exists profiles_updated_at on public.profiles;
create trigger profiles_updated_at before update on public.profiles for each row execute procedure public.set_updated_at();

drop trigger if exists submissions_updated_at on public.submissions;
create trigger submissions_updated_at before update on public.submissions for each row execute procedure public.set_updated_at();

drop trigger if exists reviews_updated_at on public.reviews;
create trigger reviews_updated_at before update on public.reviews for each row execute procedure public.set_updated_at();

drop trigger if exists reviews_refresh_rating on public.reviews;
create trigger reviews_refresh_rating after insert or update or delete on public.reviews for each row execute procedure public.refresh_tool_rating();

-- 6. ENABLE ROW LEVEL SECURITY (RLS)
alter table public.profiles enable row level security;
alter table public.tools enable row level security;
alter table public.submissions enable row level security;
alter table public.reviews enable row level security;
alter table public.sign_in_logs enable row level security;

-- Drop obsolete or permissive policies
drop policy if exists "Public Read Approved Tools" on public.tools;
drop policy if exists "Enable Insert/Update/Delete on Tools" on public.tools;
drop policy if exists "Enable Read on Sign In Logs" on public.sign_in_logs;
drop policy if exists "Enable Insert on Sign In Logs" on public.sign_in_logs;
drop policy if exists "Enable Read on Submissions" on public.submissions;
drop policy if exists "Enable Insert on Submissions" on public.submissions;
drop policy if exists "Enable Update on Submissions" on public.submissions;
drop policy if exists "Enable Read on Reviews" on public.reviews;
drop policy if exists "Enable Insert on Reviews" on public.reviews;
drop policy if exists "profiles: self or admin read" on public.profiles;
drop policy if exists "profiles: self update" on public.profiles;
drop policy if exists "tools: public approved read" on public.tools;
drop policy if exists "tools: admin insert" on public.tools;
drop policy if exists "tools: admin update" on public.tools;
drop policy if exists "tools: admin delete" on public.tools;
drop policy if exists "submissions: owner or admin read" on public.submissions;
drop policy if exists "submissions: authenticated insert" on public.submissions;
drop policy if exists "submissions: admin update" on public.submissions;
drop policy if exists "submissions: admin delete" on public.submissions;
drop policy if exists "reviews: public read" on public.reviews;
drop policy if exists "reviews: authenticated insert" on public.reviews;
drop policy if exists "reviews: owner update" on public.reviews;
drop policy if exists "reviews: owner delete" on public.reviews;
drop policy if exists "sign in logs: admin read" on public.sign_in_logs;
drop policy if exists "sign in logs: authenticated insert" on public.sign_in_logs;

-- Profiles policies
create policy "profiles: self or admin read" on public.profiles for select to authenticated using (id = auth.uid() or public.is_admin());
create policy "profiles: self update" on public.profiles for update to authenticated using (id = auth.uid()) with check (id = auth.uid());

-- Tools policies
create policy "tools: public approved read" on public.tools for select using (status = 'approved' or public.is_admin());
create policy "tools: admin insert" on public.tools for insert to authenticated with check (public.is_admin());
create policy "tools: admin update" on public.tools for update to authenticated using (public.is_admin()) with check (public.is_admin());
create policy "tools: admin delete" on public.tools for delete to authenticated using (public.is_admin());

-- Submissions policies
create policy "submissions: owner or admin read" on public.submissions for select to authenticated using (user_id = auth.uid() or public.is_admin());
create policy "submissions: authenticated insert" on public.submissions for insert to authenticated with check (user_id = auth.uid());
create policy "submissions: admin update" on public.submissions for update to authenticated using (public.is_admin()) with check (public.is_admin());
create policy "submissions: admin delete" on public.submissions for delete to authenticated using (public.is_admin());

-- Reviews policies
create policy "reviews: public read" on public.reviews for select using (true);
create policy "reviews: authenticated insert" on public.reviews for insert to authenticated with check (user_id = auth.uid());
create policy "reviews: owner update" on public.reviews for update to authenticated using (user_id = auth.uid()) with check (user_id = auth.uid());
create policy "reviews: owner delete" on public.reviews for delete to authenticated using (user_id = auth.uid());

-- Sign In Logs policies
create policy "sign in logs: admin read" on public.sign_in_logs for select to authenticated using (public.is_admin());
create policy "sign in logs: authenticated insert" on public.sign_in_logs for insert to authenticated with check (user_id = auth.uid());

-- Permissions
revoke all on table public.sign_in_logs from anon, authenticated;
grant select on public.tools, public.reviews to anon, authenticated;
grant select on public.profiles to authenticated;
grant insert, update, delete on public.tools, public.submissions, public.reviews to authenticated;
grant execute on function public.record_my_sign_in(text) to authenticated;
grant execute on function public.approve_submission(bigint) to authenticated;
grant execute on function public.is_admin() to authenticated, anon;

-- ============================================================
-- HOW TO CREATE YOUR FIRST ADMINISTRATOR:
-- 1. Register an account in the AIFinder UI or Supabase Auth dashboard.
-- 2. Find the user UUID in Supabase Auth > Users.
-- 3. Run the following SQL command in Supabase SQL Editor:
--    update public.profiles set role = 'admin' where id = '<YOUR_USER_UUID>';
-- ============================================================
